version: "3.3"

services:
  web:
    container_name: web
    image: nginx
    ports:
      - "8000:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./frontend:/var/www/static
    
  auth:
    container_name: auth
    build: ./authAPI/.

  chat:
    container_name: chat
    build: ./chatAPI/.